# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "汪鸿儒课题组"
title:              "Wang Lab at the Agricultural Genomics Institute at Shenzhen, Chinese Academy of Agricultural Sciences"
description:        "The Wang Lab is a Evolutionary Genetics and Genomics research group at  Agricultural Genomics Institute at Shenzhen, Chinese Academy of Agricultural Sciences."


# URL
url:                http://Wanglab.com
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "首页"
    href:           "/"
  - name:           "课题组介绍"
    href:           "/课题组介绍"
  - name:           "论文发表"
    href:           "/论文发表"
  - name:           "课题组成员"
    href:           "/课题组成员"
  - name:           "blog"
    href:           "/blog"
  - name:           "resources"
    href:           "/resources"
  - name:           "课题组动态"
    href:           "/课题组动态"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
